---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: fakestore
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-0.kafka.fakestore.svc.cluster.local:9092"
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: fakestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: ghcr.io/fake-store/fakestore-payments:sha-3b0d3fb
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-config
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: fakestore
spec:
  selector:
    app: payments
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
